"""Geometry for C15, the dial: the ring, its chords, the sinusoid and the three small dials."""

from __future__ import annotations

import glob

import numpy as np

from analysis.figures import style as S

RUNS = {
    "Mlp": "mlp_add97_f0.3_wd1.0_softmax_ce_s0",
    "Ref": "transformer_add113_f0.3_wd0.1_softmax_ce_s0",
    "Can": "transformer_add97_f0.3_wd1.0_softmax_ce_s0",
}
DIAL_P = 12          # the schematic dial of panel (a): a clock, and legible
EXAMPLE = (9, 5)     # 9 + 5 = 2 (mod 12), the one worked example


def terminal_embedding(run: str) -> np.ndarray:
    snaps = sorted(glob.glob(f"results/raw/{run}/snapshots/*/representations.npz"))
    if not snaps:
        raise FileNotFoundError(f"no snapshots for {run}")
    E = np.load(snaps[-1])["embedding"]
    return E - E.mean(0)


def ring(E: np.ndarray) -> dict:
    U, sv, _ = np.linalg.svd(E, full_matrices=False)
    Y = U[:, :2] * sv[:2]
    Y = Y / np.abs(Y).max()
    angle = np.degrees(np.arctan2(Y[:, 1], Y[:, 0])) % 360
    order = np.argsort(angle)                       # residues, in angular order
    p = len(order)
    steps = [(int(order[(i + 1) % p]) - int(order[i])) % p for i in range(p)]
    unique = sorted(set(steps))
    return {
        "xy": Y,
        "order": order,
        "winding": unique[0] if len(unique) == 1 else None,
        "steps": unique,
        "share": float((sv[:2] ** 2).sum() / (sv ** 2).sum()),
        "radius": float(np.hypot(*Y.T).mean()),
        "p": p,
    }


def build() -> str:
    rings = {k: ring(terminal_embedding(v)) for k, v in RUNS.items()}
    hero = rings["Mlp"]
    p = hero["p"]

    assert hero["winding"] is not None, "the hero ring is not a single clean winding"

    coord = hero["xy"][:, 0]
    coord = coord / np.abs(coord).max()
    spec = np.abs(np.fft.rfft(coord))
    spec = spec / spec[1:].max()
    peak = int(np.argmax(spec[1:]) + 1)

    lines = [
        "% Generated by analysis/figures/dial.py -- do not edit by hand.",
        "% One measurement: the top-two principal plane of three terminal embeddings.",
        "% Panel (b)'s ring, its chords, panel (c)'s sinusoid and panel (d)'s three dials",
        "% are all read off the same three matrices.",
        "",
        f"\\def\\DialP{{{DIAL_P}}}",
        f"\\def\\DialA{{{EXAMPLE[0]}}}",
        f"\\def\\DialB{{{EXAMPLE[1]}}}",
        f"\\def\\DialSum{{{sum(EXAMPLE) % DIAL_P}}}",
        "",
        f"\\def\\HeroP{{{p}}}",
        f"\\def\\HeroWinding{{{hero['winding']}}}",
        f"\\def\\HeroShare{{{hero['share']:.2f}}}",
        f"\\def\\HeroPeak{{{peak}}}",
        "",
    ]

    lines.append("\\def\\HeroPoints{" + ", ".join(
        f"{i}/{x:.4f}/{y:.4f}" for i, (x, y) in enumerate(hero["xy"])) + "}")
    quarters = [int(hero["order"][round(f * p) % p]) for f in (0, 0.25, 0.5, 0.75)]
    lines.append("\\def\\HeroCardinals{" + ", ".join(
        f"{r}/{hero['xy'][r, 0]:.4f}/{hero['xy'][r, 1]:.4f}" for r in quarters) + "}")
    lines.append("")

    xs = np.arange(p) / (p - 1)
    lines.append("\\def\\HeroWave{" + " -- ".join(
        f"({x:.4f},{0.5 + 0.5 * y:.4f})" for x, y in zip(xs, coord, strict=True)) + "}")
    ks = np.arange(len(spec)) / (len(spec) - 1)
    lines.append("\\def\\HeroSpectrum{" + ", ".join(
        f"{x:.4f}/{v:.4f}" for x, v in zip(ks, spec, strict=True)) + "}")
    lines.append(f"\\def\\HeroPeakX{{{peak / (len(spec) - 1):.4f}}}")
    lines.append("")

    for name, r in rings.items():
        lines.append(f"\\def\\{name}Points{{" + ", ".join(
            f"{i}/{x:.4f}/{y:.4f}" for i, (x, y) in enumerate(r["xy"])) + "}")
        lines.append(f"\\def\\{name}Steps{{{'--'.join(str(s) for s in r['steps'][:3])}}}")
        lines.append(f"\\def\\{name}Share{{{r['share']:.2f}}}")
        lines.append(f"\\def\\{name}Radius{{{r['radius']:.4f}}}")
        lines.append("")
    return "\n".join(lines) + "\n"


def main() -> None:
    out = S.OUTPUT_ROOT / "tikz-dial-data.tex"
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(build())
    print(f"wrote {out}")


if __name__ == "__main__":
    main()
