"""Geometry for C15, the dial.

Modular addition is rotation; a grokked network builds that dial in its embedding, but
*wound* --- laid out at some frequency rather than in residue order --- and it builds it
cleanly only in some regimes. Every coordinate the picture draws is computed here, so the
ring in panel (b), the chords threaded across it, the sinusoid in (c) and the three small
dials in (d) describe one measurement and cannot disagree with each other.

Run: ``uv run python -m analysis.figures.dial``.
"""

from __future__ import annotations

import glob

import numpy as np

from analysis.figures import style as S

RUNS = {
    "Mlp": "mlp_add97_f0.3_wd1.0_softmax_ce_s0",
    "Ref": "transformer_add113_f0.3_wd0.1_softmax_ce_s0",
    "Can": "transformer_add97_f0.3_wd1.0_softmax_ce_s0",
}
DIAL_P = 12          # the schematic dial of panel (a): a clock, and legible
EXAMPLE = (9, 5)     # 9 + 5 = 2 (mod 12), the one worked example


def terminal_embedding(run: str) -> np.ndarray:
    """The residue-embedding matrix at the last stored snapshot, centred."""
    snaps = sorted(glob.glob(f"results/raw/{run}/snapshots/*/representations.npz"))
    if not snaps:
        raise FileNotFoundError(f"no snapshots for {run}")
    E = np.load(snaps[-1])["embedding"]
    return E - E.mean(0)


def ring(E: np.ndarray) -> dict:
    """The top-two principal plane, as a ring: coordinates, order, winding, share.

    The winding is the step in *residue* taken by one step around the ring. Where the
    embedding is one clean Fourier mode that step is constant, and it is the frequency.
    """
    U, sv, _ = np.linalg.svd(E, full_matrices=False)
    Y = U[:, :2] * sv[:2]
    Y = Y / np.abs(Y).max()
    angle = np.degrees(np.arctan2(Y[:, 1], Y[:, 0])) % 360
    order = np.argsort(angle)                       # residues, in angular order
    p = len(order)
    steps = [(int(order[(i + 1) % p]) - int(order[i])) % p for i in range(p)]
    unique = sorted(set(steps))
    return {
        "xy": Y,
        "order": order,
        "winding": unique[0] if len(unique) == 1 else None,
        "steps": unique,
        "share": float((sv[:2] ** 2).sum() / (sv ** 2).sum()),
        "radius": float(np.hypot(*Y.T).mean()),
        "p": p,
    }


def _pairs(xy, scale=1.0, fmt="{:.4f}/{:.4f}") -> str:
    return ", ".join(fmt.format(scale * x, scale * y) for x, y in xy)


def build() -> str:
    rings = {k: ring(terminal_embedding(v)) for k, v in RUNS.items()}
    hero = rings["Mlp"]
    p = hero["p"]

    assert hero["winding"] is not None, "the hero ring is not a single clean winding"

    # (c) one principal coordinate against residue, and its spectrum. The coordinate is a
    # sinusoid whose frequency is the winding, which is what makes `Fourier concentration'
    # a measurement of the same fact the ring shows.
    coord = hero["xy"][:, 0]
    coord = coord / np.abs(coord).max()
    spec = np.abs(np.fft.rfft(coord))
    spec = spec / spec[1:].max()
    peak = int(np.argmax(spec[1:]) + 1)

    lines = [
        "% Generated by analysis/figures/dial.py -- do not edit by hand.",
        "% One measurement: the top-two principal plane of three terminal embeddings.",
        "% Panel (b)'s ring, its chords, panel (c)'s sinusoid and panel (d)'s three dials",
        "% are all read off the same three matrices.",
        "",
        f"\\def\\DialP{{{DIAL_P}}}",
        f"\\def\\DialA{{{EXAMPLE[0]}}}",
        f"\\def\\DialB{{{EXAMPLE[1]}}}",
        f"\\def\\DialSum{{{sum(EXAMPLE) % DIAL_P}}}",
        "",
        f"\\def\\HeroP{{{p}}}",
        f"\\def\\HeroWinding{{{hero['winding']}}}",
        f"\\def\\HeroShare{{{hero['share']:.2f}}}",
        f"\\def\\HeroPeak{{{peak}}}",
        "",
    ]

    # the ring, in residue order: index i is residue i, so a chord i -- i+1 is a step of
    # one in the group and a step of `winding' around the ring
    lines.append("\\def\\HeroPoints{" + ", ".join(
        f"{i}/{x:.4f}/{y:.4f}" for i, (x, y) in enumerate(hero["xy"])) + "}")
    # the residues sitting at the quarter turns of the ring, which is all the labelling a
    # ninety-seven-point dial can carry
    quarters = [int(hero["order"][round(f * p) % p]) for f in (0, 0.25, 0.5, 0.75)]
    lines.append("\\def\\HeroCardinals{" + ", ".join(
        f"{r}/{hero['xy'][r, 0]:.4f}/{hero['xy'][r, 1]:.4f}" for r in quarters) + "}")
    lines.append("")

    # (c) the two strips, as unit-square paths
    xs = np.arange(p) / (p - 1)
    lines.append("\\def\\HeroWave{" + " -- ".join(
        f"({x:.4f},{0.5 + 0.5 * y:.4f})" for x, y in zip(xs, coord, strict=True)) + "}")
    ks = np.arange(len(spec)) / (len(spec) - 1)
    lines.append("\\def\\HeroSpectrum{" + ", ".join(
        f"{x:.4f}/{v:.4f}" for x, v in zip(ks, spec, strict=True)) + "}")
    lines.append(f"\\def\\HeroPeakX{{{peak / (len(spec) - 1):.4f}}}")
    lines.append("")

    for name, r in rings.items():
        lines.append(f"\\def\\{name}Points{{" + ", ".join(
            f"{i}/{x:.4f}/{y:.4f}" for i, (x, y) in enumerate(r["xy"])) + "}")
        lines.append(f"\\def\\{name}Steps{{{'--'.join(str(s) for s in r['steps'][:3])}}}")
        lines.append(f"\\def\\{name}Share{{{r['share']:.2f}}}")
        # the mean radius, drawn as a guide so departure from a ring is visible rather than
        # inferred: without it a tangle and an approximate circle look alike
        lines.append(f"\\def\\{name}Radius{{{r['radius']:.4f}}}")
        lines.append("")
    return "\n".join(lines) + "\n"


def main() -> None:
    out = S.OUTPUT_ROOT / "tikz-dial-data.tex"
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(build())
    print(f"wrote {out}")


if __name__ == "__main__":
    main()
